/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as IdeaRouteImport } from './routes/idea'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IdeaSlugRouteImport } from './routes/idea.$slug'

const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeaRoute = IdeaRouteImport.update({
  id: '/idea',
  path: '/idea',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeaSlugRoute = IdeaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => IdeaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/idea': typeof IdeaRouteWithChildren
  '/saved': typeof SavedRoute
  '/idea/$slug': typeof IdeaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/idea': typeof IdeaRouteWithChildren
  '/saved': typeof SavedRoute
  '/idea/$slug': typeof IdeaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/idea': typeof IdeaRouteWithChildren
  '/saved': typeof SavedRoute
  '/idea/$slug': typeof IdeaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/idea' | '/saved' | '/idea/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/idea' | '/saved' | '/idea/$slug'
  id: '__root__' | '/' | '/idea' | '/saved' | '/idea/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IdeaRoute: typeof IdeaRouteWithChildren
  SavedRoute: typeof SavedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idea': {
      id: '/idea'
      path: '/idea'
      fullPath: '/idea'
      preLoaderRoute: typeof IdeaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idea/$slug': {
      id: '/idea/$slug'
      path: '/$slug'
      fullPath: '/idea/$slug'
      preLoaderRoute: typeof IdeaSlugRouteImport
      parentRoute: typeof IdeaRoute
    }
  }
}

interface IdeaRouteChildren {
  IdeaSlugRoute: typeof IdeaSlugRoute
}

const IdeaRouteChildren: IdeaRouteChildren = {
  IdeaSlugRoute: IdeaSlugRoute,
}

const IdeaRouteWithChildren = IdeaRoute._addFileChildren(IdeaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdeaRoute: IdeaRouteWithChildren,
  SavedRoute: SavedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
